spring:
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8021

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

management:
  endpoints:
    web:
      exposure:
        include: refresh,health