spring:
  application:
    name: green
  cloud:
    stream:
      bindings:
        output:
          destination: tasktopic
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8021

management:
  endpoints:
    web:
      exposure:
        include: refresh

app:
  task:
    launch:
      request: true