spring:
  application:
    name: green
  cloud:
    stream:
      bindings:
        output:
          destination: tasktopic

server:
  port: 8021

management:
  endpoints:
    web:
      exposure:
        include: refresh
