spring:
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8021

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # default
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

management:
  endpoints:
    web:
      exposure:
        include: refresh,health

app:
  config: green config from application.yml
