spring:
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8031

eureka:
  client:
    healthcheck:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,hystrix.stream

feign:
  hystrix:
    enabled: true
