spring:
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8031

eureka:
  client:
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,health
