version: '3.7'

services:

  green3:
    image: lishmanio/green
    ports:
      - 8023:8023
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SERVER_PORT=8023
      - APP_INSTANCE=three

  green4:
    image: lishmanio/green
    ports:
      - 8024:8024
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SERVER_PORT=8024
      - APP_INSTANCE=four
