version: '3.7'

services:

  eureka:
    image: lishmanio/eureka
    ports:
      - 8761:8761

  config-server:
    image: lishmanio/config-server
    ports:
      - 8888:8888

  zipkin:
    image: lishmanio/zipkin
    ports:
      - 9411:9411

  hystrix:
    image: lishmanio/hystrix
    ports:
      - 8900:8900

# Zuul (server?)
