
# -----------------------------------------------------------------------------
# countries collection

GET http://localhost:8021/green/countries
Accept: application/json
Content-Type: application/json

###


GET http://localhost:8021/green/countries
Accept: application/hal+json
Content-Type: application/hal+json

###



# -----------------------------------------------------------------------------
# country item

GET http://localhost:8021/green/countries/20
Accept: application/json
Content-Type: application/json

###


GET http://localhost:8021/green/countries/20
Accept: application/hal+json
Content-Type: application/hal+json

###
