
# -----------------------------------------------------------------------------
# groups collection

GET http://localhost:8021/green/countries
Content-Type: application/json

###



# -----------------------------------------------------------------------------
# groups item

GET http://localhost:8021/green/countries/20
Content-Type: application/json

###
