
# -----------------------------------------------------------------------------
# groups collection

GET http://localhost:8021/green/groups
Content-Type: application/json

###



# -----------------------------------------------------------------------------
# groups item

GET http://localhost:8021/green/groups/3
Content-Type: application/json

###
