
# -----------------------------------------------------------------------------
# people collection

GET http://localhost:8021/green/people
Content-Type: application/json

###



# -----------------------------------------------------------------------------
# people item

GET http://localhost:8021/green/people/3
Content-Type: application/json

###
