
# -----------------------------------------------------------------------------
# people collection

GET http://localhost:8021/green/people
Accept: application/json
Content-Type: application/json

###


GET http://localhost:8021/green/people
Accept: application/hal+json
Content-Type: application/hal+json

###


# -----------------------------------------------------------------------------
# people item

GET http://localhost:8021/green/people/3
Accept: application/json
Content-Type: application/json

###


GET http://localhost:8021/green/people/3
Accept: application/hal+json
Content-Type: application/hal+json

###
