
# -----------------------------------------------------------------------------
# POST group

POST http://localhost:8061/purple/api/groups
Content-Type: application/json

{
    "name": "Group Six",
    "description": "Group six description"
}

###



# -----------------------------------------------------------------------------
# POST item with data

POST http://localhost:8061/purple/api/items
Content-Type:application/json

{
    "group": "http://localhost:8061/purple/api/groups/4",
    "uuid": "9f84fa9a-4b9c-46f8-9098-4603efe7ccbc",
    "name": "Item Nine",
    "description": "Item nine description",
    "correlationId": "128a7512-0b92-4f49-8f61-15dabbd757b8",
    "status": 3,
    "data": [
        {
          "value": 11.49
        },
        {
          "category": "http://localhost:8061/purple/categories/1",
          "value": 45.76
        }
      ]
}

###
