server:
  port: 8071
  servlet:
    context-path: /white

  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # default
