

# -----------------------------------------------------------------------------
# countries collection

GET http://localhost:8081/cyan/countries
Accept: application/json

###

GET http://localhost:8081/cyan/countries
Accept: application/hal+json

###


# -----------------------------------------------------------------------------
# countries item

GET http://localhost:8081/cyan/countries/20
Accept: application/json

###

GET http://localhost:8081/cyan/countries/20
Accept: application/hal+json

###
