

# -----------------------------------------------------------------------------
# users collection

GET http://localhost:8081/cyan/users
Content-Type: application/json

###


# -----------------------------------------------------------------------------
# webflux features

GET http://localhost:8081/cyan/users/webflux

###


# -----------------------------------------------------------------------------
# latest user event (not a stream)

GET http://localhost:8081/cyan/users/latest
Content-Type: application/json

###
