

# -----------------------------------------------------------------------------
# countries, WebClient

GET http://localhost:8081/cyan/countries
Accept: application/json

###

GET http://localhost:8081/cyan/countries/20
Accept: application/json

###



# -----------------------------------------------------------------------------
# countries, WebClient, HAL
#
# Note: the client (in the service) uses HAL but the contents
# are returned as plain JSON from this request

GET http://localhost:8081/cyan/countries?format=hal
Accept: application/json

###

GET http://localhost:8081/cyan/countries/20?format=hal
Accept: application/json

###



# -----------------------------------------------------------------------------
# stats, WebClient, merge

GET http://localhost:8081/cyan/stats
Content-Type: application/json

###



# -----------------------------------------------------------------------------
# POST, WebClient

POST http://localhost:8081/cyan/countries
Content-Type: application/json

{
  "code": "OB",
  "name": "Some Obscure Country"
}

###



# -----------------------------------------------------------------------------
# PUT, WebClient
#
# See response from POST above for id

PUT http://localhost:8081/cyan/countries/{id}
Content-Type: application/json

{
  "code": "OX",
  "name": "Updated obscure country name"
}

###



# -----------------------------------------------------------------------------
# DELETE, WebClient
#
# See response from POST above for id


DELETE http://localhost:8081/cyan/countries/{id}

###
