

# -----------------------------------------------------------------------------
# countries, WebClient, JSON

GET http://localhost:8081/cyan/countries
Accept: application/json

###

GET http://localhost:8081/cyan/countries/20
Accept: application/json

###



# -----------------------------------------------------------------------------
# countries, WebClient, HAL
#
# Note: the client (in the service) uses HAL but the contents
# are returned as plain JSON from this request

GET http://localhost:8081/cyan/countries?format=hal
Accept: application/json

###

GET http://localhost:8081/cyan/countries/20?format=hal
Accept: application/json

###



# -----------------------------------------------------------------------------
# stats, merge

GET http://localhost:8081/cyan/stats
Content-Type: application/json

###



# -----------------------------------------------------------------------------
# POST, WebClient

POST http://localhost:8081/cyan/countries
Content-Type: application/json

{
  "code": "OB",
  "name": "Some Obscure Country"
}

###



# -----------------------------------------------------------------------------
# PUT, WebClient

PUT http://localhost:8081/cyan/countries/10
Content-Type: application/json

{
  "code": "AG",
  "name": "Antigua & Barbuda"
}

###



# -----------------------------------------------------------------------------
# DELETE, WebClient

DELETE http://localhost:8081/cyan/countries/262

###
