

# -----------------------------------------------------------------------------
# users, WebClient, WebFlux

GET http://localhost:8081/cyan/users
Content-Type: application/json

###


# Get a UUID from White service console output

GET http://localhost:8081/cyan/users/{UUID}
Content-Type: application/json

###


# -----------------------------------------------------------------------------
# users, multiple calls to WebFlux API

GET http://localhost:8081/cyan/users/webflux

###


# -----------------------------------------------------------------------------
# event streams

# Toggle the event stream on and off
POST http://localhost:8081/cyan/users/events/toggle
Content-Type: application/json

###


# Get the latest event
GET http://localhost:8081/cyan/users/events/latest
Content-Type: application/json

###
