

# -----------------------------------------------------------------------------
# users, Flux

GET http://localhost:8081/cyan/users
Content-Type: application/json

###


GET http://localhost:8081/cyan/users/{UUID}
Content-Type: application/json

###


# -----------------------------------------------------------------------------
# webflux features

GET http://localhost:8081/cyan/users/webflux

###


# -----------------------------------------------------------------------------
# latest user event

GET http://localhost:8081/cyan/users/latest
Content-Type: application/json

###
