
# -----------------------------------------------------------------------------
# categories collection

GET http://localhost:8061/purple/api/categories
Content-Type: application/json

###



# -----------------------------------------------------------------------------
# categories item

GET http://localhost:8061/purple/api/categories/3
Content-Type: application/json

###

