
# -----------------------------------------------------------------------------
# Paging & sorting

GET http://localhost:8061/purple/api/countries?page=5&size=3&sort=code,desc
Content-Type: application/json

###



# -----------------------------------------------------------------------------
# Searching, paging, sorting & projection

GET http://localhost:8061/purple/api/items/search/findByGroupName?groupNameContains=gro&page=1&size=3&sort=name,desc&projection=totals
Content-Type: application/json

###
