server:
  port: 8081
  servlet:
    context-path: /cyan

spring:
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # default

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,hystrix.stream
