spring:
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8011

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # default

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,hystrix.stream

app:
  logfile:
    location: ${user.home}/lishman/ref/logs/filebeat
