spring:
  application:
    name: blue
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8011

security:
  oauth2:
    resource:
      user-info-uri: https://api.github.com/user
    client:
      clientId: blue

management:
  endpoints:
    web:
      exposure:
        include: refresh

app:
  config: blue application.yml config


