spring:
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8011

eureka:
  client:
    healthcheck:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh,health


