spring:
  application:
    name: blue
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8011

management:
  endpoints:
    web:
      exposure:
        include: refresh

app:
  config: blue application.yml config


