spring:
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8011

eureka:
  client:
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,health

app:
  config: blue config from application.yml


