server:
  port: 8061
  servlet:
    context-path: /purple

spring:
  data:
    rest:
      basePath: /api
  sleuth:
    sampler:
      probability: 1.0

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        default_schema: purple
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # default

app:
  config: green config from application.yml
  logfile:
    location: ${user.home}/lishman/ref/logs/filebeat
