
# -----------------------------------------------------------------------------
# users, Feign

GET http://localhost:8081/cyan/users?client=feign
Content-Type: application/json

###

GET http://localhost:8081/cyan/users/2?client=feign
Content-Type: application/json

###
