

# -----------------------------------------------------------------------------
# employees, WebClient, WebFlux

GET http://localhost:8081/cyan/employees
Content-Type: application/json

###


# Get a UUID from White service console output

GET http://localhost:8081/cyan/employees/{id}
Content-Type: application/json

###


# -----------------------------------------------------------------------------
# employees, multiple calls to WebFlux API

GET http://localhost:8081/cyan/employees/webflux

###


# -----------------------------------------------------------------------------
# event streams

# Toggle the event stream on and off
POST http://localhost:8081/cyan/employees/events/toggle
Content-Type: application/json

###


# Get the latest event
GET http://localhost:8081/cyan/employees/events/latest
Content-Type: application/json

###
