
# -----------------------------------------------------------------------------
# users

GET http://localhost:8021/green/users
Accept: application/json


###
GET http://localhost:8021/green/users/677777
Accept: application/json

###



# -----------------------------------------------------------------------------
# employee, HAL

GET http://localhost:8021/green/users
Accept: application/hal+json

###


GET http://localhost:8021/green/users/5
Accept: application/hal+json

###



# -----------------------------------------------------------------------------
# POST

POST http://localhost:8021/green/users
Content-Type: application/json

{
  "firstName": "Mick",
  "lastName": "Wishman",
  "userName": "mickywise",
  "email": "micky.wiseman@email.com",
  "phoneNumber": "024---618-1244",
  "age": 20,
  "website": "wiseman.com"
}

###



# -----------------------------------------------------------------------------
# PUT

PUT http://localhost:8021/green/users/{id}
Content-Type: application/json

{
  "firstName": "Micky",
  "lastName": "Wiseman",
  "userName": "Micky.Wise",
  "email": "micky.wiseman@email.com",
  "phoneNumber": "024-618-1244",
  "age": 23,
  "website": "wiseman.net"
}

###



# -----------------------------------------------------------------------------
# DELETE

DELETE http://localhost:8021/green/users/{id}

###
