spring:
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8041

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # default

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,hystrix.stream

ribbon:
  eureka:
    enabled: false

# ribbon disabled, config below used instead

pink-client:
  ribbon:
    listOfServers: localhost:8051,localhost:8052

app:
  config: orange config from application.yml