spring:
  application:
    name: orange

server:
  port: 8041

ribbon:
  eureka:
    enabled: false

pink-client:
  ribbon:
    listOfServers: localhost:8051,localhost:8052

management:
  endpoints:
    web:
      exposure:
        include: refresh