spring:
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8041

eureka:
  client:
    healthcheck:
      enabled: false

ribbon:
  eureka:
    enabled: false

# ribbon disabled, config below used instead

pink-client:
  ribbon:
    listOfServers: localhost:8051,localhost:8052

management:
  endpoints:
    web:
      exposure:
        include: refresh,health

app:
  config: orange config from application.yml